Adding default service/topic/action to each node
aprotyas/nodl_to_policy pull request #7
Opened 2021-06-24 23:00 UTC by aprotyas

Fixes #6.

Signed-off-by: Abrar Rahman Protyasha <abrar@openrobotics.org>

2021-06-28 17:38 UTC, aprotyas commented
FYI, some talking points:

- I had to manually add the common profile XMLs to this repository because they are not registered to ament index through `sros2`. ros2/sros2#147 lays the bedding for that, but for time reasons and because it's stale, I opted to go with the current solution. If that PR gets merged (and I'm happy to look at it once there's time), the common profile XMLs in the `_common` folder can be removed from this repository.
- What to do about the difference between node "type"s? I'm primarily thinking of node vs lifecycle node, since they have a different set of "common" permissions. I have thoughts about implementing it (some grounding in `types.py` and `_common/_profile.py`), but haven't done so because there doesn't seem to be much talk of a `LifecycleNode` tag in ros2/design#266.

2021-06-28 19:11 UTC, clalancette requested changes
I've left a few inline comments.

2021-06-28 19:11 UTC, clalancette commented on nodl_to_policy/_common/_profile.py
> +        return path
This is a strange pattern; usually a `with` statement is used to keep a resource around for a while.  In this case, since we are returning it, the resource can be freed immediately on return.  What exactly is this code trying to accomplish?

2021-06-28 19:11 UTC, clalancette commented on nodl_to_policy/_common/_profile.py
> +__common_request_services: Optional[List] = None
Having all of these global python objects is an unusual pattern.  What exactly are we trying to accomplish with all of these globals?

2021-06-28 19:11 UTC, clalancette commented on nodl_to_policy/policy.py
> +from typing import Dict, List, Union, Tuple
Nit: alphebetize (`Union` comes after `Tuple`)

2021-06-28 19:11 UTC, clalancette commented on package.xml
> +  <exec_depend>python3-lxml</exec_depend>
Nit: alphabetical order

2021-06-28 21:21 UTC, aprotyas commented on nodl_to_policy/policy.py
> +from typing import Dict, List, Union, Tuple
Fixed.

2021-06-28 21:25 UTC, aprotyas commented on package.xml
> +  <exec_depend>python3-lxml</exec_depend>
Fixed.

2021-06-28 21:34 UTC, aprotyas commented on nodl_to_policy/_common/_profile.py
> +        return path
I was unsure about this too, but the `importlib` [API documentation](https://docs.python.org/3/library/importlib.html#importlib.resources.path) says "This function returns a context manager for use in a `with` statement", which is why I used this pattern.

2021-06-28 22:16 UTC, aprotyas commented on nodl_to_policy/_common/_profile.py
> +        return path
I see where you're coming from, though. I reckon this would just be clearer:
```suggestion
    return importlib_resources.path('nodl_to_policy._common', filename)
```

2021-06-28 22:17 UTC, aprotyas commented on nodl_to_policy/_common/_profile.py
> +__common_request_services: Optional[List] = None
I was trying to design these as static objects that require setup only once. Is there a way to do this with a more limited scope?

2021-06-30 14:53 UTC, clalancette commented on nodl_to_policy/_common/_profile.py
> +        return path
The documentation says:

```
Exiting the context manager cleans up any temporary file created when the resource needs to be extracted from e.g. a zip file.
```

Which is why it is a context manager and not just a simple string.

Honestly, given how short this method is, I'll suggest just removing the method completely and open-coding the `with` statement in the one place you need it.  That way it will still be a context manager (and hence will cleanup after itself), and you'll still get the functionality you need.

2021-06-30 14:59 UTC, clalancette commented on nodl_to_policy/_common/_profile.py
> +__common_request_services: Optional[List] = None
So essentially what you are trying to do is to [memoize](https://en.wikipedia.org/wiki/Memoization) these lists.  Python has tools builtin for this: https://docs.python.org/3/library/functools.html .

All of that said, this may be premature optimization.  Unless you know this is a performance problem, I'd suggest just calling `_get_{profile,items_by_role}` as needed and not bothering with the memoization.

2021-06-30 15:15 UTC, aprotyas commented on nodl_to_policy/_common/_profile.py
> +__common_request_services: Optional[List] = None
Since we haven't hit a wall with performance problems (and don't anticipate to given how infrequent this operation should be...), I'll change the pattern so there's no memoization involved.

2021-06-30 16:31 UTC, aprotyas commented on nodl_to_policy/_common/_profile.py
> +        return path
Fixed in 25d9db8.

2021-06-30 16:32 UTC, aprotyas commented on nodl_to_policy/_common/_profile.py
> +__common_request_services: Optional[List] = None
Addressed in b54b125.

2021-06-30 16:35 UTC, aprotyas commented
@clalancette final check of the changes in 25d9db8 and in b54b125?

2021-06-30 21:50 UTC, clalancette approved these changes

2021-06-30 21:51 UTC, merged